version: '3.7'

services:
  redis:
    image: ${IMAGE_REDIS}
    container_name: infra-redis
    restart: "always"
    volumes:
      - /docker/storage/storage-infra-redis/data:/data
    ports:
      - 6379:6379
    networks:
      - lan-network

  postgres:
    image: ${IMAGE_POSTGRES}
    container_name: infra-postgres
    restart: "always"
    volumes:
      - /docker/storage/storage-infra-postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - lan-network

networks:
  lan-network:
    external:
      name: docker-net