name: Push InvioEmailSvc to DockerHub

on:
  push:
    branches: [ main ]
    paths: 
       - 'src/InvioEmailSvc/InvioEmailSvc/**'
       - 'src/InvioEmailSvc/InvioEmailSvc.BusinessLayer/**'
       - 'src/InvioEmailSvc/InvioEmailSvc.DataAccessLayer/**'
       - 'src/InvioEmailSvc/InvioEmailSvc.Migrations/**'
       - 'src/InvioEmailSvc/InvioEmailSvc.Shared/**'
  workflow_dispatch:

jobs:
  build:
    name: Push images to DockerHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Build and push Invio Email
        uses: docker/build-push-action@v6.9.0
        with:
         context: .
         file: ./src/InvioEmailSvc/InvioEmailSvc/Dockerfile
         push: true
         tags: ${{ secrets.DOCKER_USERNAME }}/gswca-invioemail:latest
